project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - "*.qmd"

website:
  title: "Home Credit Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01_data_map.qmd
        text: Data Map

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    toc-title: "Contents"
    code-fold: true
    code-summary: "Show code"
    embed-resources: true

execute:
  echo: true
  warning: false
  message: false

