project:
  type: website
  output-dir: _site

website:
  title: "Home Credit Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    toc-title: "Contents"
    code-fold: true
    code-summary: "Show code"

execute:
  echo: true
  warning: false
  message: false