project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - "index.qmd"
    - "01_data_map.qmd"
    - "02_industry_context.qmd"
    - "03_eda_plan.qmd"

website:
  title: "Home Credit Project Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01_data_map.qmd
        text: Data Map
      - href: 02_industry_context.qmd
        text: Industry Context
      - href: 03_eda_plan.qmd
        text: EDA Plan

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    toc-location: left
    toc-title: "Contents"
    code-fold: true
    code-summary: "Show code"
    embed-resources: true

execute:
  echo: true
  warning: false
  message: false

